DEFINE_JSON_STRUCT_BEGIN( Vec3 )
	DEF_JSON_ITEM_NUMBER(x)
	DEF_JSON_ITEM_NUMBER(y)
	DEF_JSON_ITEM_NUMBER(z)
DEFINE_JSON_STRUCT_END

DEFINE_JSON_STRUCT_BEGIN(PlayerData)
	DEF_JSON_ITEM_STRING(name)
	DEF_JSON_ITEM_OBJECT( Vec3, position )
	DEF_JSON_ITEM_NUMBER(weight)
	DEF_JSON_ITEM_BOOL(alive)
DEFINE_JSON_STRUCT_END